---
title: "Task1"
author: "Dmytro Sadovnychenko"
date: "14/10/2024"
format:
  html:
    embed-resources: true
editor: source
---

## Question 1 

```{r}
my_char <- "Kris"
my_numeric <- 32.5
my_integer <- 88L
my_complex <- 6 + 4i
my_logical <- TRUE

c(my_char, my_numeric, my_integer, my_complex, my_logical)
```
## Question 2
```{r}
seq_5_to_75 <- seq(5, 75)
my_numbers <- c(3.14, 2.71, 0, 13)
true_values <- rep(TRUE, 100)

seq_5_to_75
my_numbers
true_values
```
## Question 3
```{r}
my_matrix <- matrix(c(12, 34, 87, -12, -12.1, 0, 3.6, 0.5, 1.3), nrow = 3, ncol = 3)
print(my_matrix)
```
## Question 4
```{r}

char <- c("Josh", "Duke")
numeric <- c(2.5, 8.5)
integer <- c(1980L, 8L)
complex <- c(9+4i, 20+7i)
logical <- c(FALSE, TRUE)
 
my_list <- list(char, numeric, integer, complex, logical)

print(my_list)
```
## Qustion 5
```{r}

age_factor <- factor(c("infant", "child", "adult"), levels = c("infant", "child", "adult"))
print(age_factor)
```
## Question 6
```{r}

my_data_frame <- data.frame(
  Name = c("Aiden", "Rosemary", "Carlos"),
  Age = c(20, 15, 31),
  Gender = c("Male", "Female", "Male"),
  Hight = c(175.9, 160.3, 182.8)
)
print(my_data_frame)


```

## Question 7
```{r}
colnames(my_data_frame) <- c('Student_Name','Student_Age','Student_Gender', 'Student_Hight')
print(my_data_frame)

```
